config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  resources :games
  resources :carts, only: [:index, :create, :destroy]
  resources :cart_items, only: [:destroy]
  resources :wishlists, only: [:index, :create, :destroy]
  resources :wishlist_items, only: [:destroy]

# stripe
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  get '/:username', to: 'users#show', as: :username
  
  root to: "users#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can [:index, :show, :new, :create], Game
    can [:edit, :update, :destroy], Game, user_id: user.id

    can :manage, :all if user.is_admin == true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :games, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  has_many :cart_items
  has_many :carts, through: :cart_items

  has_many :wishlist_items
  has_many :wishlists, through: :wishlist_items

  def self.search(search)
    if search
      user = User.find_by(username: search)
      if user
        self.where(user_id: user)
      else
        Game.all
      end
    else
      Game.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, dependent: :destroy

  has_one :cart, dependent: :destroy

  has_one :wishlist, dependent: :destroy

  validates :username, presence: true, uniqueness: true
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many :wishlist_items
  has_many :games, through: :wishlist_items
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
  belongs_to :wishlist
  belongs_to :game
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @user = current_user
    # Checks if the user is signed in and already has an active cart
    if user_signed_in? && current_user.cart
      @cart = current_user.cart.games.includes([:image_attachment])
    else
      flash[:no_cart] = "You currently don't have any items in your cart"
      redirect_to request.referer
    end
  end

  def create
    # Checks if the user has a cart, if they do it loads that cart.
    if !current_user.cart
      cart = Cart.create(completed: false, user_id: current_user.id)
    else
      cart = current_user.cart
    end
    game = Game.find(params[:game_id])
    game.in_cart = true
    cart.games << game
    flash[:added_item] = "Successfully added item to your cart!"
    redirect_to request.referer
  end

  def destroy
    @cart = current_user.cart
    @cart.cart_item.destroy
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # At the bottom of the page there is a method that will be ran before each of the method's listed after the ":only"
  before_action :find_game, only: [:show, :edit, :update, :destroy]
  # This will set the list of all available platforms.
  before_action :platforms, only: [:new, :edit]
  load_and_authorize_resource

  def index
    # Using the search query I created it will list games with only the search parameter inserted
    @games = Game.search(params[:search])
  end

  def show
  end

  def new
    @game = Game.new
  end

  def create
    @game = current_user.games.create(game_params)
    # Sets the posted_by variable to be the current users username.
    @game.posted_by = current_user.username
    # Multiplies the cost the user inserts by 100 (to turn it into cents)
    @game.cost = @game.cost * 100
    # If the game has been appropriately filled out it will save the game, if not it will refresh the page and display the error message.
    if @game.save
      redirect_to @game
      flash[:success] = "You successfully created a new game!"
    else
      flash[:failed] = "You failed to create a new game!:("
      redirect_to request.referer
    end
  end

  def edit
    # This will display the games cost in an appropriate value.
    @game.cost = @game.cost / 100
  end

  def update
    if @game.update(game_params)
      # Ensures the value is converted to cents
      @game.update(cost: (@game.cost * 100))
      redirect_to game_path(@game)
    else
      redirect_to request.referer
      flash[:failed] = "You failed to update a new game!:("
    end
  end

  def destroy
    @game.destroy
    redirect_to root_path
  end

  private

  def game_params
    # Only allows these fields to be changed when creating a new game.
    params.require(:game).permit(:title, :platform, :cost, :username, :image)
  end

  def find_game
    @game = Game.find(params[:id])
  end

  def platforms
    @platforms = [
      "macOS", "Game Boy Advance", "Xbox One", "Xbox", "Windows", "Nintendo DS", "GameCube", "Nintendo 64", "PlayStation Portable", "Game Gear", "PlayStation 2", "Nintendo DSi", "Sega Master System", "Super Nintendo Entertainment System", "Virtual Boy", "Wii", "Xbox 360", "Game Boy", "PlayStation 3", "PlayStation 4", "PlayStation Vita", "Game Boy Color", "Linux", "Sega Dreamcast", "Sega Genesis", "Nintendo Entertainment System", "Nintendo Switch", "Wii U", "Nintendo 3DS", "PlayStation", "Sega Saturn"
    ]
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # Allows stripe to work with webhooks without an authenticity token
  skip_before_action :verify_authenticity_token, only: [:webhook]
  def success
    @cart = current_user.cart
    # If the page successfully load it changes each game in the database to be sold
    @cart.games.each do |game|
      game.is_sold == true
    end
    @cart.destroy
  end

  def webhook
    payment_id = params[:data][:object][:payment_intent]
    payment = Stripe::PaymentIntent.retrieve(payment_id)
    game_id = payment.metadata.game_id
    user_id = payment.metadata.user_id

    p "game id " + game_id
    p "user id " + user_id

    head 200
  end

  def get_stripe_id
    counter = 0
    line_items = []
    @cart = Cart.find(current_user.cart.id)
    @cart.games.length.times do
      hash = { name: @cart.games[counter].title,
               amount: @cart.games[counter].cost,
               currency: 'aud',
               quantity: 1 }
      line_items << hash
      counter += 1
    end
    session_id = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user.email,
      line_items: line_items,

      payment_intent_data: {
        metadata: {
          user_id: current_user.id,
          cart_id: @cart.user_id
        }
      },
      success_url: "#{root_url}payments/success?userId=#{current_user.id}&gameId=#{@cart.id}",
      cancel_url: "#{root_url}games"
    ).id
    render :json => { id: session_id, stripe_public_key: Rails.application.credentials.dig(:stripe, :public_key) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # Lists all games by cost.
    @games = Game.order(:cost).includes([:image_attachment, :user]).page(params[:page])
  end

  def show
    if user_signed_in?
      @user = User.where(username: params[:username])[0]
    else
      @user = User.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlist_items_helper.rb
module WishlistItemsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= favicon_link_tag asset_path('favicon.png') %>
    <title>BuyGGz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <%= flash[:no_cart] %>
      <%= flash[:added_item] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_card.html.erb
<% if game.in_cart != true %>
  <div class="card" style="width: 18rem;">
    <% if game.image.attached? %>
     <img class="card-img-top" alt='picture of' <% game.title %><%= image_tag game.image %>
    <% else %>
      <img class="card-img-top" alt='Default image' <%= image_tag "default_image.png" %> 
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to game.title, game_path(game.id)%></h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Price: $<%= (game.cost / 100).round(2)%></li>
      <li class="list-group-item">Console: <%= game.platform %></li>
      <li class="list-group-item"><%= link_to game.posted_by, username_path(game.user.username) %></li>
    </ul>
         <% if current_user.is_admin == true%>
       <div class="card-body">
        <%= link_to 'Add to cart', carts_path(game_id: game.id), method: :post %>
        </div>
        <% if game.in_wishlist != true %>
         <div class="card-body">
          <%= link_to 'Add to wishlist', wishlists_path(game_id: game.id), method: :post %>
        </div>
        <% else %>
          <div class="card-body">
            <%= link_to "Remove from wishlist", wishlist_item_path(game.id), method: :delete%>
          </div>
        <% end %>

        <div class="card-body">
        <div class="show-edit-delete">
          <%= link_to "Edit", edit_game_path(game.id) %>
          <%= link_to "Delete", game_path(game.id), method: :delete %>
        </div>

      <% else %>
      <% if can? :edit, game %>
        <div class="card-body">
          <div class="show-edit-delete">
            <%= link_to "Edit", edit_game_path(game.id) %>
            <%= link_to "Delete", game_path(game.id), method: :delete %>
          </div>
        </div>
      <% else %>
        <div class="card-body">      
          <%= link_to 'Add to cart', carts_path(game_id: game.id), method: :post %>
        </div>
        <% if game.in_wishlist != true %>
         <div class="card-body">
          <%= link_to 'Add to wishlist', wishlists_path(game_id: game.id), method: :post %>
        </div>
        <% else %>
          <div class="card-body">
            <%= link_to "Remove from wishlist", wishlist_item_path(game.id), method: :delete%>
          </div>
        <% end %>

      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: @game, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :cost %>
    <%= form.number_field :cost%>
  </div>

  <div>
    <%= form.label :platform %>
    <%= form.select :platform, @platforms%>
  </div>

<div>
  <%= form.label :image %> 
  <%= form.file_field :image, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
</div>

  <div>
   <%= form.submit %>  
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Home", root_path, class:"navbar-brand "%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "/#{current_user.username}", class: "nav-link" do %>
                  <%= current_user.username.capitalize %>
              <% end %>
            </li>
            <li class="nav-item"><%= link_to "🎁", wishlists_path, class: "nav-link" %></li>

            <li class="nav-item"><%= link_to "New Game", new_game_path, class: "nav-link" %></li>


        <% end %>
        <li class="nav-item">
            <% if user_signed_in? %>
                <%= link_to "Sign out", destroy_user_session_path, class: 'nav-link', method: :delete %>
            <% else %>
                <%= link_to "Sign in", new_user_session_path, class: 'nav-link' %>
            <% end %>
        </li>
        <% if !user_signed_in? %>
            <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %></li>
        <% end %>
        <%= form_tag(games_path, method: :get) do %>
          <%= text_field_tag(:search, params[:search])%>
          <%= submit_tag ("Search")%>
        <% end %>
        <li class="nav-item"><%= link_to "🛒", carts_path, class: "nav-link" %></li>
    </ul>
  </div>
</nav>