config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  resources :games
  resources :carts, only: [:index, :create, :destroy]
  resources :cart_items, only: [:destroy]
  resources :wishlists, only: [:index, :create, :destroy]
  resources :wishlist_items, only: [:destroy]

# stripe
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  get '/:username', to: 'users#show', as: :username
  
  root to: "users#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :games, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @user = current_user
    # Checks if the user is signed in and already has an active cart
    if user_signed_in? && current_user.cart
      @cart = current_user.cart.games.includes([:image_attachment])
    else
      flash[:no_cart] = "You currently don't have any items in your cart"
      redirect_to request.referer
    end
  end

  def create
    # Checks if the user has a cart, if they do it loads that cart.
    if !current_user.cart
      cart = Cart.create(completed: false, user_id: current_user.id)
    else
      cart = current_user.cart
    end
    game = Game.find(params[:game_id])
    game.in_cart = true
    cart.games << game
    flash[:added_item] = "Successfully added item to your cart!"
    redirect_to request.referer
  end

  def destroy
    @cart = current_user.cart
    @cart.cart_item.destroy
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<%= render 'shared/navbar' %>
<h1> <%= @user.username %>'s cart </h1>


<% @cart.each do |game| %>
  <div class="card" style="width: 18rem;">
    <% if game.image.attached? %>
      <img class="card-img-top" alt='picture of' <% game.title %><%= image_tag game.image %>
    <% else %>
      <img class="card-img-top" alt='Default image' <%= image_tag "default_image.png" %> 
    <% end %>
  </div>

  <ul>
     <li><%= link_to game.title, game_path(game.id) %></li>
     <li><%= number_to_currency(game.cost / 100) %></li>
     <%= link_to "Remove from cart", cart_item_path(game.id), method: :delete%>
  </ul>
<% end %>


<%= link_to "Checkout", "", id: "stripe" %> 
<%= javascript_pack_tag "stripe" %>  